plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "E:\\megha projects\\e-commerce-new\\frontend\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "E:\\megha projects\\e-commerce-new\\frontend"
command = "npm run build"

[build.environment]
  VITE_API_URL = "https://e-commerce-new-n4qx.onrender.com/api"
  VITE_RAZORPAY_KEY_ID = "rzp_test_SLpaaErOmLqmHK"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]